### ISSUE TITLE
数据采集

### ISSUE THREAD

**Issue by huming0618** [huming0618/ds-shop#5]
使用手机设备对产品信息进行采集

### 参考
[Android 端基于 OpenCV 的边框识别功能](https://pqpo.me/2017/09/11/opencv-border-recognition/?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io)

**Comment by huming0618** [comment]
## IOS App
- 视频捕获
- 实时处理
  - 识别
  - 压缩
- 上传

**Comment by huming0618** [comment]
## IOS App 开发

了解图像处理开发
http://www.cnblogs.com/mar-q/p/6670052.html
https://www.youtube.com/watch?v=ywUBHqxwM5Q
https://www.youtube.com/watch?v=ca4uEKtOrcE
https://medium.com/compileswift/ios-opencv-and-swift-1ee3e3a5735b

文本识别
http://blog.csdn.net/youxitongyongming/article/details/51548882?locationNum=2&fps=1

OpenCV 
https://saitoxu.io/2016/11/07/how-to-use-opencv-in-swift-2.html

Object Detection
https://www.toptal.com/machine-learning/real-time-object-detection-using-mser-in-ios

mac上安装opencv3
http://www.pyimagesearch.com/2016/12/19/install-opencv-3-on-macos-with-homebrew-the-easy-way/

Repo
https://github.com/huming0618/swift-camera-opencv.git

CIFeature
https://blog.xamarin.com/image-detection-in-ios-8/

**Comment by huming0618** [comment]
## 了解手机相机的设置(iOS)

### 帧速率

> 帧速率是指每秒钟刷新的图片的帧数，也可以理解为图形处理器每秒钟能够刷新几次。对影片内容而言，帧速率指每秒所显示的静止帧格数

帧速率可以影响到CPU使用率和电池消耗

### 问题
##### 在什么样的帧速率下捕获才是合适的?
##### 合适的曝光模式?
##### 合适的对焦模式?
##### 如何得知已经对焦?
```
使用isAdjustingFocus
[Refer] https://stackoverflow.com/questions/24719553/detect-when-camera-is-auto-focusing
```

### API
##### [activeVideoMinFrameDuration](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1389290-activevideominframeduration)
> A device’s minimum frame duration is the reciprocal of its maximum frame rate. You can set the value of this property to limit the maximum frame rate during a capture session.

##### [activeVideoMaxFrameDuration](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1387816-activevideomaxframeduration)
> A device’s maximum frame duration is the reciprocal of its minimum frame rate. You can set the value of this property to limit the minimum frame rate during a capture session. 

##### [activeFormat](https://developer.apple.com/documentation/avfoundation/avcapturedevice/1389221-activeformat)
> The currently active media data format of the capture device.

##### [FocusMode](https://developer.apple.com/documentation/avfoundation/avcapturedevice.focusmode)
```

case locked: The focus is locked.
case autoFocus: The device automatically adjusts the focus once and then changes the focus mode to 
locked
.
case continuousAutoFocus: The capture device continuously monitors focus and auto focuses when necessary.
```

##### [AVCaptureFlashMode](https://developer.apple.com/documentation/avfoundation/avcaptureflashmode?preferredLanguage=occ)

##### [AVCaptureExposureMode](https://developer.apple.com/documentation/avfoundation/AVCaptureExposureMode?preferredLanguage=occ)
```

case locked
The exposure setting is locked.

case autoExpose
The device automatically adjusts the exposure once and then changes the exposure mode to 
locked
.
case continuousAutoExposure
The device continuously monitors exposure levels and auto exposes when necessary.

case custom
The device should only adjust exposure according to user provided 
iso andexposureDuration property values.
```

##### [WhiteBalanceMode](https://developer.apple.com/documentation/avfoundation/avcapturedevice.whitebalancemode)

参考
- [opencv教程 ](http://www.opencv.org.cn/opencvdoc/2.3.2/html/doc/tutorials/imgproc/threshold/threshold.html)
- [CMTimeMake](https://stackoverflow.com/questions/4001755/trying-to-understand-cmtime-and-cmtimemake)
- [ios自定义相机](http://www.jianshu.com/p/8b28892bae5a)
- [240FPS](http://taylorfranklin.me/2015/01/20/ios-tutorial-developing-240-fps/)
- [iphone6 camera new feature](https://developer.apple.com/library/content/technotes/tn2409/_index.html)

**Comment by huming0618** [comment]
## 图像识别与机器学习

- [ ] 学习预期目标
- [ ] 如何搭建
- [ ] 如何与App结合

### Log
- mac 安装opencv [参考](https://segmentfault.com/a/1190000007761481)

**Comment by huming0618** [comment]
## App 功能 ToDo
- [ ] 横竖屏控制 [参考](http://www.chinabooks99.top/index.php/2016/07/29/swfit-xuanbing-control/)
- [ ] 拍照保存功能
- [ ] 识别条形码 [参考](https://stackoverflow.com/questions/838724/how-can-i-scan-barcodes-on-ios)
- [ ] 识别文本

## Note
API for detection on ios/osx
https://developer.apple.com/documentation/coreimage
https://developer.apple.com/documentation/coreimage/citextfeature
https://developer.apple.com/documentation/coreimage/cidetector
https://developer.apple.com/documentation/coreimage/cirectanglefeature

Sample Code
https://github.com/shu223/iOS-9-Sampler/blob/master/iOS9Sampler/SampleViewControllers/TextDetectViewController.swift

文本识别
https://github.com/Wang-Shuo/Chinese-Text-Detection-and-Recognition
https://github.com/tianzhi0549/CTPN

recognition with tesseract 
https://www.raywenderlich.com/93276/implementing-tesseract-ocr-ios

For iOS11
https://github.com/hollisliu/iOS-Vision-Text-Detection-Demo

For Barcode
http://www.th7.cn/Program/IOS/201604/794354.shtml

OpenCV Barcode
http://www.pyimagesearch.com/2014/11/24/detecting-barcodes-images-python-opencv/
http://felix.abecassis.me/2011/10/opencv-barcode-reader-part-3/

**Comment by huming0618** [comment]
## Note
Caffe
https://github.com/solrex/caffe-mobile

**Comment by huming0618** [comment]
## Barcode检测问题
尝试使用opencv检测Barcode
参考　http://www.pyimagesearch.com/2014/11/24/detecting-barcodes-images-python-opencv/

- [ ] 条码区域检测
- [ ] 条码块读取

## 问题解决策略
- 理解OpenCV处理中每个API的基本原理
- 理解API的参数
- 理解示例中的思路
- 调试，验证

**Comment by huming0618** [comment]
### OpenCV学习

https://github.com/huming0618/learn-opencv3

**Comment by huming0618** [comment]
## 使用ios11 Vison来建立检测系统

### 示例程序
- https://github.com/huming0618/IOS11-BarcodeDetection
- https://github.com/huming0618/IOS11-TextDetection

### To-Do
- [ ] 了解Vision API 以及检测的局限性
- [ ] 文本识别
- [ ] 如何与机器学习结合
- [ ] Demo 同时检测条形码和检测文本

### Tesseract 参考
- https://www.youtube.com/watch?v=DTQ1z_8KXZo
- [Installation](https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation)
- [Example](https://www.raywenderlich.com/93276/implementing-tesseract-ocr-ios)
- Another LIb - https://github.com/garnele007/SwiftOCR
